# Generated by Django 3.1.7 on 2021-03-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0002_auto_20210301_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, upload_to='timetable/')),
                ('std', models.IntegerField()),
            ],
            options={
                'ordering': ['std'],
            },
        ),
    ]
