# Generated by Django 3.1.7 on 2021-03-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0005_auto_20210301_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='excel_file',
        ),
        migrations.AddField(
            model_name='timetable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
